#!/bin/bash

# Auto-Build Environment Setup
# Feature: Activity Taxonomy Explorer and Enhanced Autofill
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Feature: Activity Explorer + Autofill"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/Users/dg/Desktop/insight-5.2"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

# Check if node_modules exist
if [ ! -d "$PROJECT_ROOT/apps/desktop/node_modules" ]; then
    echo -e "${YELLOW}Installing desktop dependencies...${NC}"
    cd "$PROJECT_ROOT/apps/desktop" && npm install
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Desktop App..."

# Desktop App (React + Vite)
cd "$PROJECT_ROOT/apps/desktop" && npm run dev &
DESKTOP_PID=$!

wait_for_service 5174 "Desktop App"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Desktop App:  http://localhost:5174"
echo ""
echo "Key Files to Modify:"
echo "  - apps/desktop/src/App.tsx"
echo "  - apps/desktop/src/App.css"
echo ""
echo "Reference Files:"
echo "  - packages/shared/src/taxonomy.ts (STARTER_TAXONOMY)"
echo "  - apps/desktop/src/learning/enricher.ts (enrichEvent)"
echo ""
echo "To stop: kill $DESKTOP_PID"
echo ""

# Keep script running
wait $DESKTOP_PID
