#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 001 - Parsing Engine Analysis and Optimization

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Parsing Engine Optimization Spec"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# Navigate to project root
cd "$(dirname "$0")/../../.."
PROJECT_ROOT=$(pwd)

echo ""
echo "Project root: $PROJECT_ROOT"
echo ""

# ============================================
# CHECK PREREQUISITES
# ============================================

echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}Node.js: $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}npm: $(npm --version)${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

# Install root dependencies
if [ -f "package.json" ]; then
    npm install --silent 2>/dev/null || true
fi

# Install parser package dependencies
if [ -d "packages/parser" ]; then
    cd packages/parser
    if [ -f "package.json" ]; then
        npm install --silent 2>/dev/null || true
    fi
    cd "$PROJECT_ROOT"
fi

# Install desktop app dependencies
if [ -d "apps/desktop" ]; then
    cd apps/desktop
    if [ -f "package.json" ]; then
        npm install --silent 2>/dev/null || true
    fi
    cd "$PROJECT_ROOT"
fi

echo -e "${GREEN}Dependencies installed${NC}"

# ============================================
# BUILD PARSER PACKAGE
# ============================================

echo ""
echo "Building parser package..."

cd packages/parser
if [ -f "package.json" ]; then
    if npm run build 2>/dev/null; then
        echo -e "${GREEN}Parser package built${NC}"
    else
        echo -e "${YELLOW}Parser build script not found or failed (may be OK if no build step)${NC}"
    fi
fi
cd "$PROJECT_ROOT"

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting development services..."

# Desktop App (Vite on port 5174)
echo "Starting Desktop App..."
cd apps/desktop
npm run dev &
DESKTOP_PID=$!
cd "$PROJECT_ROOT"

# Wait for desktop to be ready
wait_for_service 5174 "Desktop App"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Desktop App:  http://localhost:5174"
echo ""
echo "Key Files for this spec:"
echo "  packages/parser/src/types.ts"
echo "  packages/parser/src/pipeline/classifier.ts"
echo "  packages/parser/src/context/habit-context.ts"
echo "  packages/parser/src/context/project-context.ts"
echo "  packages/parser/src/confidence/scorer.ts"
echo "  apps/desktop/src/nlp/natural.ts"
echo "  apps/desktop/src/nlp/llm-parse.ts"
echo ""
echo "Process IDs:"
echo "  Desktop: $DESKTOP_PID"
echo ""
echo "To stop services, run: kill $DESKTOP_PID"
echo ""
