#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Obsidian-Style Note View with Google Docs Navigation

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Navigate to project root
cd "$(dirname "$0")/../../.."

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
cd apps/desktop
npm install
cd ../..

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Desktop App (web mode)..."

# Desktop App (React + Vite)
cd apps/desktop
npm run dev:web &
DESKTOP_PID=$!
cd ../..

# Wait for Desktop to be ready
wait_for_service 5174 "Desktop App"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Desktop App: http://localhost:5174"
echo ""
echo "To stop all services: kill $DESKTOP_PID"
echo ""
echo "Development Commands:"
echo "  TypeScript Check: cd apps/desktop && npx tsc --noEmit"
echo "  Lint:            cd apps/desktop && npm run lint"
echo "  Build:           cd apps/desktop && npm run build"
echo ""
