#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Project: Notes Explorer Redesign - Obsidian-Style File Explorer

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"
echo ""
echo "Feature: Notes Explorer Redesign"
echo "Service: Desktop App (React + Vite)"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/Users/dg/Desktop/insight-5.2"
DESKTOP_DIR="$PROJECT_ROOT/apps/desktop"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start after ${max}s${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# PRE-FLIGHT CHECKS
# ============================================

echo ""
echo "Running pre-flight checks..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm --version)${NC}"

# Check desktop directory exists
if [ ! -d "$DESKTOP_DIR" ]; then
    echo -e "${RED}Desktop app directory not found: $DESKTOP_DIR${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Desktop app directory exists${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

if [ ! -d "$DESKTOP_DIR/node_modules" ]; then
    echo "Installing desktop app dependencies..."
    cd "$DESKTOP_DIR" && npm install
else
    echo -e "${GREEN}✓ Dependencies already installed${NC}"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting desktop app..."

# Kill any existing process on port 5174
if lsof -i :5174 > /dev/null 2>&1; then
    echo -e "${YELLOW}Stopping existing process on port 5174...${NC}"
    lsof -ti :5174 | xargs kill -9 2>/dev/null || true
    sleep 2
fi

# Start desktop dev server
cd "$DESKTOP_DIR" && npm run dev &
DESKTOP_PID=$!

# Wait for desktop app to be ready
wait_for_service 5174 "Desktop App"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Desktop App: http://localhost:5174"
echo ""
echo "Files to modify:"
echo "  - apps/desktop/src/workspace/views/notes.tsx"
echo "  - apps/desktop/src/App.tsx"
echo "  - apps/desktop/src/App.css"
echo "  - apps/desktop/src/workspace/pane.tsx"
echo ""
echo "Files to delete:"
echo "  - apps/desktop/src/workspace/views/people.tsx"
echo "  - apps/desktop/src/workspace/views/places.tsx"
echo "  - apps/desktop/src/workspace/views/tags.tsx"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait $DESKTOP_PID
