#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Feature: UI Consistency & Multi-Select Item Properties

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Feature: UI Consistency & Multi-Select"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
cd "$PROJECT_ROOT"

echo -e "${YELLOW}Project root: $PROJECT_ROOT${NC}"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start after ${max}s${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi

if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}Node.js and npm found${NC}"

# ============================================
# INSTALL DEPENDENCIES (if needed)
# ============================================

if [ ! -d "node_modules" ]; then
    echo ""
    echo "Installing root dependencies..."
    npm install
fi

if [ ! -d "apps/desktop/node_modules" ]; then
    echo ""
    echo "Installing desktop app dependencies..."
    cd apps/desktop && npm install && cd ../..
fi

echo -e "${GREEN}Dependencies installed${NC}"

# ============================================
# START DESKTOP SERVICE
# ============================================

echo ""
echo "Starting Desktop App (web only)..."
cd apps/desktop

# Kill any existing process on port 5174
lsof -ti:5174 | xargs kill -9 2>/dev/null || true

# Start Vite dev server in background
npm run dev:web &
DESKTOP_PID=$!

cd ../..

# Wait for service to be ready
wait_for_service 5174 "Desktop App"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Desktop App: http://localhost:5174"
echo ""
echo "Development Commands:"
echo "  TypeScript check: cd apps/desktop && npx tsc --noEmit"
echo "  Lint:            cd apps/desktop && npm run lint"
echo "  Build:           cd apps/desktop && npm run build"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running and forward signals
trap "echo 'Stopping services...'; kill $DESKTOP_PID 2>/dev/null; exit 0" SIGINT SIGTERM

wait $DESKTOP_PID
