/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Figtree"', 'ui-sans-serif', 'system-ui'],
      },
      colors: {
        bg: 'var(--bg)',
        panel: 'var(--panel)',
        panel2: 'var(--panel2)',
        border: 'var(--border)',
        border2: 'var(--border2)',
        text: 'var(--text)',
        muted: 'var(--muted)',
        muted2: 'var(--muted2)',
        accent: 'var(--accent)',
        accentSoft: 'var(--accentSoft)',
        indigo: 'var(--indigo)',
        clay: 'var(--accent)',
      },
      // 8pt Grid Spacing System
      spacing: {
        'px': '1px',
        '0': '0',
        '0.5': '2px',
        '1': '4px',
        '1.5': '6px',
        '2': '8px',
        '2.5': '10px',
        '3': '12px',
        '3.5': '14px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '9': '36px',
        '10': '40px',
        '12': '48px',
        '14': '56px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
        '32': '128px',
        // Semantic spacing
        'stack-xs': '4px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'stack-xl': '32px',
        'inline-xs': '4px',
        'inline-sm': '8px',
        'inline-md': '12px',
        'inline-lg': '16px',
        // Responsive page spacing (via CSS vars)
        'page': 'var(--page-margin)',
        'gutter': 'var(--page-gutter)',
        // Safe area utilities
        'safe-t': 'var(--safe-area-top)',
        'safe-r': 'var(--safe-area-right)',
        'safe-b': 'var(--safe-area-bottom)',
        'safe-l': 'var(--safe-area-left)',
      },
      boxShadow: {
        glass: '0 24px 60px rgba(15, 23, 42, 0.18)',
      },
      borderRadius: {
        xl: '12px',
        '2xl': '16px',
      },
    },
  },
  plugins: [],
}
