#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 005: Mobile App UI/UX Improvements

set -e

echo "========================================"
echo "Starting Insight Mobile Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project paths
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
MOBILE_APP_PATH="${PROJECT_ROOT}/apps/insight-mobile"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# VERIFY PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}Node.js: $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}npm: $(npm --version)${NC}"

# Check expo-cli (optional but helpful)
if command -v expo &> /dev/null; then
    echo -e "${GREEN}Expo CLI available${NC}"
else
    echo -e "${YELLOW}Expo CLI not found globally (will use npx)${NC}"
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

# Root dependencies
cd "${PROJECT_ROOT}"
if [ -f "package-lock.json" ]; then
    npm ci
else
    npm install
fi

# Mobile app dependencies
cd "${MOBILE_APP_PATH}"
if [ -f "package-lock.json" ]; then
    npm ci
else
    npm install
fi

# ============================================
# CHECK ENVIRONMENT VARIABLES
# ============================================

echo ""
echo "Checking environment variables..."

if [ -f "${MOBILE_APP_PATH}/.env.local" ]; then
    echo -e "${GREEN}.env.local found${NC}"
else
    echo -e "${YELLOW}Warning: .env.local not found in apps/insight-mobile${NC}"
    echo "You may need to create it with:"
    echo "  EXPO_PUBLIC_SUPABASE_URL=<your-url>"
    echo "  EXPO_PUBLIC_SUPABASE_ANON_KEY=<your-key>"
fi

# ============================================
# START EXPO DEV SERVER
# ============================================

echo ""
echo "Starting Expo development server..."

cd "${MOBILE_APP_PATH}"

# Start Expo in the background
npx expo start --ios &
EXPO_PID=$!

# Wait for Metro bundler to be ready
wait_for_service 8081 "Metro Bundler"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Development Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Metro Bundler:  http://localhost:8081"
echo "  Expo Dev URL:   exp://localhost:8081"
echo ""
echo "Quick Commands:"
echo "  Press 'i' in terminal to open iOS simulator"
echo "  Press 'a' to open Android emulator"
echo "  Press 'w' to open in web browser"
echo ""
echo "Working Directory: ${MOBILE_APP_PATH}"
echo ""
echo "To stop: Press Ctrl+C or kill process ${EXPO_PID}"
echo ""

# Keep script running
wait $EXPO_PID
