#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Feature: ChatGPT-Style Life Planner Engine

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES (if needed)
# ============================================

echo ""
echo "Checking dependencies..."

cd apps/desktop

# Check if new dependencies need to be installed
if ! npm list react-dropzone >/dev/null 2>&1 || ! npm list pdf-parse >/dev/null 2>&1; then
    echo -e "${YELLOW}Installing new dependencies...${NC}"
    npm install react-dropzone@^14 pdf-parse@^1.1.1
fi

cd ../..

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Desktop App..."

# Desktop (React + Vite + Electron)
cd apps/desktop && npm run dev &
DESKTOP_PID=$!

wait_for_service 5174 "Desktop App"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Desktop App:  http://localhost:5174"
echo ""
echo "Process IDs:"
echo "  Desktop:      $DESKTOP_PID"
echo ""
echo "To stop all services: kill $DESKTOP_PID"
echo ""
echo "========================================"
echo "Development Notes:"
echo "========================================"
echo ""
echo "Key files to modify:"
echo "  - apps/desktop/src/workspace/views/assistant.tsx  (main UI)"
echo "  - apps/desktop/src/openai.ts                      (API calls)"
echo "  - apps/desktop/src/assistant/storage.ts           (types)"
echo ""
echo "Pattern files to reference:"
echo "  - apps/desktop/src/storage/nutrition.ts           (confidence scoring)"
echo "  - apps/desktop/src/storage/tasks.ts               (task creation)"
echo "  - apps/desktop/src/storage/calendar.ts            (event creation)"
echo ""
echo "========================================"

# Keep script running
wait
